# Generated by Django 3.2.13 on 2022-06-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_signal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockChainAddress',
        ),
    ]
